import type { Property } from "./types";

export const PROPERTIES: Property[] = [
  {
    id: 1,
    slug: "apartment-sale-elmahalla-city-center",
    title: "شقة للبيع - قلب المحلة الكبرى",
    location: "المحلة الكبرى، شارع البحر",
    type: "sale",
    price: "1,250,000 جنيه",
    areaM2: 145,
    bedrooms: 3,
    bathrooms: 2,
    description:
      "شقة مميزة في موقع حيوي بالقرب من الخدمات. مناسبة للسكن العائلي مع تشطيب جيد وإضاءة طبيعية ممتازة.",
    features: ["موقع حيوي", "قريبة من الخدمات", "تهوية ممتازة", "عداد كهرباء ومياه"],
    images: ["/placeholders/property.svg"],
    isFeatured: true,
  },
  {
    id: 2,
    slug: "apartment-rent-elmahalla-university-area",
    title: "شقة للإيجار - قرب الجامعة",
    location: "المحلة الكبرى، منطقة الجامعة",
    type: "rent",
    price: "6,500 جنيه / شهر",
    areaM2: 110,
    bedrooms: 2,
    bathrooms: 1,
    description:
      "شقة إيجار بالقرب من الجامعة والمواصلات. مناسبة للموظفين أو عائلة صغيرة.",
    features: ["قريبة من المواصلات", "مطبخ واسع", "أمن جيد"],
    images: ["/placeholders/property.svg"],
    isFeatured: true,
  },
  {
    id: 3,
    slug: "shop-rent-elmahalla-main-street",
    title: "محل للإيجار - شارع رئيسي",
    location: "المحلة الكبرى، شارع رئيسي",
    type: "shops",
    price: "12,000 جنيه / شهر",
    areaM2: 48,
    description:
      "محل واجهة مميزة على شارع رئيسي مناسب للأنشطة التجارية المختلفة.",
    features: ["واجهة زجاج", "موقع تجاري", "كثافة مرور عالية"],
    images: ["/placeholders/property.svg"],
  },
  {
    id: 4,
    slug: "land-sale-gharbia-investment",
    title: "قطعة أرض للبيع - فرصة استثمار",
    location: "الغربية، قرب المحلة الكبرى",
    type: "lands",
    price: "سعر قابل للتفاوض",
    areaM2: 250,
    description:
      "قطعة أرض مناسبة للبناء أو الاستثمار، موقع جيد وقريبة من طرق رئيسية.",
    features: ["قريبة من الطرق", "مساحة ممتازة", "مناسبة للاستثمار"],
    images: ["/placeholders/property.svg"],
    isFeatured: true,
  },
  {
    id: 5,
    slug: "apartment-sale-elmahalla-new-area",
    title: "شقة للبيع - منطقة هادئة",
    location: "المحلة الكبرى، منطقة سكنية هادئة",
    type: "sale",
    price: "980,000 جنيه",
    areaM2: 120,
    bedrooms: 3,
    bathrooms: 1,
    description:
      "شقة في منطقة هادئة مناسبة للعائلات، قريبة من المدارس والخدمات الأساسية.",
    features: ["منطقة هادئة", "قريبة من المدارس", "تشطيب جيد"],
    images: ["/placeholders/property.svg"],
  },
  {
    id: 6,
    slug: "apartment-rent-elmahalla-furnished",
    title: "شقة مفروشة للإيجار",
    location: "المحلة الكبرى، قرب الخدمات",
    type: "rent",
    price: "9,000 جنيه / شهر",
    areaM2: 95,
    bedrooms: 2,
    bathrooms: 1,
    description:
      "شقة مفروشة جاهزة للسكن فورًا، مناسبة للمدة الطويلة أو القصيرة حسب الاتفاق.",
    features: ["مفروشة بالكامل", "جاهزة للسكن", "قريبة من الخدمات"],
    images: ["/placeholders/property.svg"],
  },
  {
    id: 7,
    slug: "exchange-apartment-elmahalla-upgrade",
    title: "تبادل عقاري - ترقية لمساحة أكبر",
    location: "المحلة الكبرى",
    type: "exchange",
    price: "تبادل + فرق حسب الاتفاق",
    areaM2: 160,
    bedrooms: 3,
    bathrooms: 2,
    description:
      "خيار تبادل عقاري مناسب لمن يرغب في الترقية لمساحة أكبر مع تفاهم واضح على الفرق.",
    features: ["تبادل مرن", "مناسب للترقية", "تفاهم واضح على الفرق"],
    images: ["/placeholders/property.svg"],
  },
  {
    id: 8,
    slug: "shop-sale-elmahalla-busy-area",
    title: "محل للبيع - منطقة حيوية",
    location: "المحلة الكبرى، منطقة حيوية",
    type: "shops",
    price: "1,600,000 جنيه",
    areaM2: 55,
    description:
      "محل للبيع في منطقة حيوية يصلح للاستثمار أو التشغيل الفوري.",
    features: ["منطقة حيوية", "مناسب للاستثمار", "تشطيب جيد"],
    images: ["/placeholders/property.svg"],
  },
  {
    id: 9,
    slug: "land-sale-elmahalla-near-road",
    title: "أرض للبيع - قرب طريق رئيسي",
    location: "قرب المحلة الكبرى",
    type: "lands",
    price: "سعر مميز",
    areaM2: 180,
    description:
      "أرض بموقع ممتاز بالقرب من طريق رئيسي، مناسبة لبناء سكني أو مشروع صغير.",
    features: ["قرب طريق رئيسي", "موقع ممتاز", "سعر مميز"],
    images: ["/placeholders/property.svg"],
  },
];
